[Home Header] Improvements 2
beatmasterRS/skin.arctic.zephyr.mod pull request #446
Opened 2021-08-04 10:31 UTC by Nanomani

Count "TV Show" added :  

before 

![1](https://user-images.githubusercontent.com/3939543/128166231-19385209-b608-4d0a-a8f0-ed2fe0c34184.jpg)

after

![2](https://user-images.githubusercontent.com/3939543/128166255-b1a39a4c-9eff-447c-b794-707f876439ce.jpg)

2021-08-04 12:11 UTC, beatmasterRS requested changes

2021-08-04 12:11 UTC, beatmasterRS commented on 1080i/Includes_Furniture.xml
> -        <value>[COLOR=$VAR[ColorHighlight]]$INFO[Window(home).Property(Movies.Count)][/COLOR] $LOCALIZE[20342]  •  [COLOR=$VAR[ColorHighlight]]$INFO[Window(home).Property(Episodes.Count)][/COLOR] $LO
A few changes need to be made:

- please don't replace the episodes count (3082)
- a wrong localized string is used for tvshows (3070)

2021-08-04 12:35 UTC, Nanomani commented
I hope it is good this time ...

2021-08-05 22:03 UTC, Nanomani commented
I have try to add "TV shows" playlist with your advise [https://forum.kodi.tv/showthread.php?tid=337862&pid=3053004#pid3053004](url)

This seems simple. :)

But with :  
`<content>plugin://script.embuary.helper/?info=getpathstats&amp;path=$INFO[Container(300).ListItem.Property(path)]&amp;prefix=PlaylistStats</content>`

(I have use a Label just after this code. So I m sure that this code is read.)

the result of this :
```
Window(Home).Property(PlaylistStats_TVShowCount)
Window(Home).Property(PlaylistStats_Episodes)
Window(Home).Property(PlaylistStats_UnwatchedEpisodes)
```
is empty. 

Anyway it is probably in my side. Nothing urgent here. 
You have other thing to do. It is only for sharing ...
I will keep looking ...

2021-08-11 06:49 UTC, beatmasterRS commented
Looks good, thank you :)

2021-08-11 06:49 UTC, merged