[Home Header] Improvements "Favourites"
beatmasterRS/skin.arctic.zephyr.mod pull request #450
Opened 2021-08-05 19:28 UTC by Nanomani

![screenshot00014](https://user-images.githubusercontent.com/3939543/128408739-9fef1707-d0f8-4463-85ea-40265451d472.png)

- need "script.favourites" (Repo Kodi)

![screenshot00015](https://user-images.githubusercontent.com/3939543/128409291-67ecc333-9b21-45be-aaf4-80fc3619919c.png)

- a review is needed :)

2021-08-05 19:35 UTC, Nanomani commented on 1080i/Home.xml
> +    <onload condition="System.HasAddon(script.favourites)">RunScript(script.favourites)</onload>
I m not sure if it is the better place ...

2021-08-05 19:40 UTC, beatmasterRS commented
- no need to add a dependency, that is not required for the main skin
- check if the addon is enabled to prevent an empty string

:)

2021-08-11 09:21 UTC, Nanomani commented
@beatmasterRS, I know that seems empty. :/

There is the same with weather : 

![1](https://user-images.githubusercontent.com/3939543/129004022-063d68d2-d589-4d55-8687-c1274536fa9b.jpg)

2021-08-11 18:26 UTC, Nanomani commented
@beatmasterRS this one is finished too
I don't know doing better :/

2021-08-11 18:33 UTC, beatmasterRS requested changes
Something must be wrong with this condition:

>>String.IsEqual(Container(300).ListItem.Property(defaultID),$LOCALIZE[1036])

if i set change this to 

>>true

all is working fine

2021-08-11 19:16 UTC, Nanomani commented
> Something must be wrong with this condition:
> 
> > > String.IsEqual(Container(300).ListItem.Property(defaultID),$LOCALIZE[1036])
> 
> if i set change this to
> 
> > > true
> 
> all is working fine

Something is wrong ?  
Tested with english french and german language. All works well ...
But if you think an other way is better please you can change the code. :)

I have use this code because for favourite the default ID is 1036 like this :  
`<property name="defaultID">1036</property>`

2021-08-11 19:24 UTC, beatmasterRS commented
Must the homemenu entry also set to favourites, or has only the widget content set to favourites?

2021-08-11 19:39 UTC, Nanomani commented
Only the main menu must set to "Favourites". The widgets can be what you want.

![screenshot00010](https://user-images.githubusercontent.com/3939543/129091967-0e5ac6a9-d0ca-4e8c-b43d-18f6591ace48.png)

![screenshot00002](https://user-images.githubusercontent.com/3939543/129091982-310167c4-bde2-4ad2-984b-29174069cefc.png)

![screenshot00003](https://user-images.githubusercontent.com/3939543/129092001-b7816753-d5a0-44cb-aae1-054d338a2164.png)

![screenshot00010](https://user-images.githubusercontent.com/3939543/129092016-20b548f1-9a16-4a64-b8d4-f9df17f5f5b9.png)

2021-08-11 19:43 UTC, Nanomani commented
Damned you are right. I delete the widget then this don't works. :/ 
Okay I look this ...

2021-08-11 19:57 UTC, beatmasterRS commented
ah okay, then this was my fault, sorry, just saw on your screenshot the widget content :D

2021-08-12 08:41 UTC, Nanomani commented
I thinks is good this time :)

2021-08-17 14:20 UTC, merged